"use client"

import "./globals.css"; // Import your global styles where the fonts are defined
import Provider from "./provider";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { usePathname } from "next/navigation"; // Import the hook for path detection



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // Get the current path

  // Check if the path is for sign-in or sign-up
  const isAuthPage = pathname === "/sign-in" || pathname === "/sign-up";

  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-[#080D27] text-[#c3caf4]">
          <Provider>
            {/* Only show Header if not on sign-in or sign-up pages */}
            {!isAuthPage && <Header />}
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}













// import type { Metadata } from "next";
// import "./globals.css"; // Import your global styles where the fonts are defined
// import Provider from "./provider";
// import Header from "@/components/Header";
// import { ClerkProvider } from "@clerk/nextjs";

// export const metadata: Metadata = {
//   title: "Ai Kid SAAS Genrator",
//   description: "Generated by Umer Qadoos",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body className="bg-[#080D27] text-[#c3caf4]"> {/* Removed Kid_Font className */}
//           <Provider>
//             <Header />
//             {children}
//           </Provider>
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }






// // import type { Metadata } from "next";
// // // import localFont from "next/font/local";
// // import "./globals.css";
// // import Provider from "./provider";
// // import { Sen } from "next/font/google"
// // import Header from "@/components/Header";
// // import {
// //   ClerkProvider
// // } from '@clerk/nextjs'

// // const Kid_Font = Sen({
// //   weight: '400',
// //   subsets: ['latin'],
// // });



// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <ClerkProvider>
// //     <html lang="en">
// //       <body
// //         className={` bg-[#080D27] ${Kid_Font.className}`}
// //       >
// //         <Provider>
// //   <Header/>

// //         {children}
// //         </Provider>
// //       </body>
// //     </html>
// //     </ClerkProvider>
// //   );
// // }
